In [30]:
from data_handling import text_dataset_loader
import importlib
importlib.reload(text_dataset_loader)


<module 'data_handling.text_dataset_loader' from '/Users/vinayak/Development/nlp_drift_paper_code/data_handling/text_dataset_loader.py'>

In [31]:
import pandas as pd
import numpy as np

from data_handling.text_dataset_loader import TextDatasetLoader

data_loader = TextDatasetLoader(tfds_dataset='ag_news_subset')
data_loader.load_data()
data_loader.convert_bytes_to_string()
data_raw= data_loader.get_data()
print(data_raw.head(5))


2023-06-07 12:18:45.225698: W tensorflow/core/kernels/data/cache_dataset_ops.cc:856] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


description
label
title
                                         description  label  \
0   CHARLOTTE, N.C. (Sports Network) - Carolina P...      1   
1   PRESENTACION, Philippines (Reuters) - Philipp...      0   
2  SAN FRANCISCO, CA - November 30, 2004 -Ubisoft...      3   
3  DANIEL VETTORI spun New Zealand to the brink o...      1   
4  AFP - Georgian and South Ossetian forces overn...      0   

                                               title  
0               Carolina's Davis Done for the Season  
1      Philippine Rebels Free Troops, Talks in Doubt  
2          New Rainbow Six Franchise for Spring 2005  
3                          Kiwis heading for big win  
4  Shelling, shooting resumes in breakaway Georgi...  


In [33]:
print(data['description'].dtype)

object


In [32]:

# Convert the text column from bytes to string
#data['description'] = data['description'].str.decode('utf-8')
data_raw.to_csv('/Users/vinayak/Development/nlp_drift_paper_code/datasets/ag_news_subset_test.csv',header=True, index=False)


In [4]:
data.head()


description  label  \
0  AMD #39;s new dual-core Opteron chip is design...      3   
1  Reuters - Major League Baseball\Monday announc...      1   
2  President Bush #39;s  quot;revenue-neutral quo...      2   
3  Britain will run out of leading scientists unl...      3   
4  London, England (Sports Network) - England mid...      1   

                                            title  
0       b'AMD Debuts Dual-Core Opteron Processor'  
1           b"Wood's Suspension Upheld (Reuters)"  
2  b'Bush reform may have blue states seeing red'  
3            b"'Halt science decline in schools'"  
4                      b'Gerrard leaves practice'

In [37]:
%load_ext autoreload
%autoreload 2
import importlib

import sentence_embedder
importlib.reload(sentence_embedder)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


<module 'sentence_embedder' from '/Users/vinayak/Development/nlp_drift_paper_code/sentence_embedder.py'>

In [20]:
import pandas as pd
import numpy as np
#Get the embeddings
data = pd.read_csv('/Users/vinayak/Development/nlp_drift_paper_code/datasets/ag_news_subset_test.csv')

In [21]:
data.head()

description  label  \
0   CHARLOTTE, N.C. (Sports Network) - Carolina P...      1   
1   PRESENTACION, Philippines (Reuters) - Philipp...      0   
2  SAN FRANCISCO, CA - November 30, 2004 -Ubisoft...      3   
3  DANIEL VETTORI spun New Zealand to the brink o...      1   
4  AFP - Georgian and South Ossetian forces overn...      0   

                                               title  
0               Carolina's Davis Done for the Season  
1      Philippine Rebels Free Troops, Talks in Doubt  
2          New Rainbow Six Franchise for Spring 2005  
3                          Kiwis heading for big win  
4  Shelling, shooting resumes in breakaway Georgi...

In [34]:
from sentence_embedder import SentenceEmbedder
embedder = SentenceEmbedder()

# Train the TF-IDF vectorizer
embedder.train_tfidf_vectorizer(data['description'].iloc[:3000])

# Generate TF-IDF vectors
tfidf_vectors = embedder.generate_tfidf_vectors(data['description'].iloc[3000:])

# Save the TF-IDF vectors to a CSV file
embedder.save_embeddings_to_csv(tfidf_vectors, "/Users/vinayak/Development/nlp_drift_paper_code/embeddings/ag_news_subset_tfidf.csv")

# Load the TF-IDF vectors from the CSV file
loaded_tfidf_vectors = embedder.load_embeddings_from_csv("/Users/vinayak/Development/nlp_drift_paper_code/embeddings/ag_news_subset_tfidf.csv")

# Print the loaded TF-IDF vectors
print(loaded_tfidf_vectors)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [40]:
embedder.save_model(embedder.tfidf_vectorizer, filename='/Users/vinayak/Development/nlp_drift_paper_code/embedding_objects/ag_news_tfidf.pkl')

In [43]:
embedder=SentenceEmbedder()
embedder.load_tfidf_vectorizer('/Users/vinayak/Development/nlp_drift_paper_code/embedding_objects/ag_news_tfidf.pkl')

In [44]:
# Generate TF-IDF vectors
tfidf_vectors = embedder.generate_tfidf_vectors(data['description'].iloc[3000:])

In [46]:
print(tfidf_vectors)

  (0, 10414)	0.20582443999301683
  (0, 10288)	0.301657408922
  (0, 9614)	0.24572335638793905
  (0, 8368)	0.1921159655406194
  (0, 7321)	0.26424325897485
  (0, 7315)	0.18492207497891144
  (0, 6783)	0.19140294615911
  (0, 6604)	0.16603714160388852
  (0, 6386)	0.301657408922
  (0, 5645)	0.22395967955964655
  (0, 5411)	0.1686689040958524
  (0, 5401)	0.24877661959137432
  (0, 4059)	0.1635752922047255
  (0, 3909)	0.29068365364016285
  (0, 3437)	0.301657408922
  (0, 2445)	0.17409761705502874
  (0, 2115)	0.22929095842686303
  (0, 1062)	0.29068365364016285
  (1, 10642)	0.2517910331041187
  (1, 10553)	0.38926484375888076
  (1, 9555)	0.23374485234119272
  (1, 9345)	0.25824235658105416
  (1, 8247)	0.38926484375888076
  (1, 7333)	0.36855291555896713
  (1, 7179)	0.28304301838864165
  :	:
  (4598, 7338)	0.29592939949664193
  (4598, 6572)	0.2851640189201056
  (4598, 6392)	0.22137046430732416
  (4598, 5736)	0.2357024569763941
  (4598, 4138)	0.1857452440330521
  (4598, 3241)	0.2473087966152286
  (4598, 

In [7]:
tfidf_vectors_df=pd.DataFrame(tfidf_vectors.toarray())

In [8]:
tfidf_vectors_df.head()

0      1      2      3      4      5      6      7      8      9      ...  \
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   

   17525  17526  17527  17528  17529  17530  17531  17532  17533  17534  
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[5 rows x 17535 columns]

In [13]:
from data_handling.embeddings_loader import EmbeddingLoader
embedding_loader=EmbeddingLoader('/Users/vinayak/Development/nlp_drift_paper_code/embeddings/ag_news_subset_tfidf.pkl')

In [14]:
tfidf_embeddings=embedding_loader.load_embeddings()

In [48]:
print(tfidf_embeddings)

  (0, 13684)	0.17577645392453714
  (0, 13150)	0.2261627443430986
  (0, 8086)	0.23007013929280912
  (0, 11862)	0.21267388818474417
  (0, 13829)	0.17443584612280286
  (0, 13072)	0.3067321455604178
  (0, 10179)	0.20971799523151446
  (0, 4597)	0.26224707452220675
  (0, 14884)	0.2877772571624484
  (0, 2307)	0.18048156416281924
  (0, 13482)	0.18810291383428782
  (0, 11450)	0.3179636466818577
  (0, 3428)	0.2578225678253903
  (0, 10693)	0.18028971431171842
  (0, 14720)	0.19281839010733137
  (0, 10608)	0.32508172933519097
  (0, 3621)	0.29802031647260513
  (1, 6897)	0.1442025570247568
  (1, 15320)	0.16778240431352734
  (1, 11593)	0.199297470819625
  (1, 4100)	0.21517118075842234
  (1, 12895)	0.2632629481270592
  (1, 16894)	0.18203544759416088
  (1, 13697)	0.13647482942053524
  (1, 10294)	0.14977152617939643
  :	:
  (7598, 11928)	0.23103788841350742
  (7598, 5279)	0.21024284667337864
  (7598, 10681)	0.2578651468721754
  (7598, 10387)	0.19779827955071222
  (7598, 9286)	0.19010608507007445
  (7598,

In [49]:
tfidf_vectors.dtype

dtype('float64')

In [51]:
tfidf_vectors.shape

(4600, 10800)

In [53]:
tfidf_embeddings_df=pd.DataFrame(tfidf_vectors.toarray())
print(tfidf_embeddings_df.head())

   0      1      2      3      4      5      6      7      8      9      ...  \
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   

   10790  10791  10792  10793  10794  10795  10796  10797  10798  10799  
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[5 rows x 10800 columns]
